### ISSUE TITLE
Invalid dates under Unworkshop titles

### ISSUE THREAD

**Issue by mbackendal** [tobiasgrosser/mental-strength-unworkshop#1]
All Unworkshops currently have "Invalid date, Invalid date-Invalid date (UK), Invalid date-Invalid date (CH)" written under the title. Both in the list of events and when viewing each individual event.
![image](https://user-images.githubusercontent.com/32503377/121195021-8a2c0d80-c86f-11eb-9a24-a70ed9ee7c5e.png)

**Comment by tobiasgrosser** [comment]
Thank you @mbackendal for the report. For me, this works on both android and my Linux system. Maybe this is some timezone issue. I will investigate this as soon as I can.

**Comment by tobiasgrosser** [comment]
@mbackendal, I managed to reproduce this issue with Firefox and believe this is now fixed. Thank you again for reporting this! I will close this issue now. Feel free to reopen or report a new bug in case this problem has not yet been solved for you.
